name: attendance_app

description: Flutter client for Attendance (Teacher & Student)
publish_to: "none"
version: 0.1.0+1
environment: { sdk: ">=3.3.0 <4.0.0" }
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter: { sdk: flutter }
  dio: ^5.7.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  mobile_scanner: ^5.2.3

  qr_flutter: ^4.1.0
  intl: ^0.20.2
  permission_handler: ^11.3.1
  http: ^1.2.1
  provider: ^6.1.2
#  camera: ^0.10.5+9
#  google_mlkit_face_detection: ^0.9.0
  tflite_flutter: ^0.10.4
  tflite_flutter_processing: ^0.4.1
#  image: ^4.2.0
  path_provider: ^2.1.4
  camera: ^0.10.6 # (hoặc phiên bản mới nhất)
  google_mlkit_face_detection: ^0.11.0
  image: ^4.0.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/models/mobile_face_net.tflite
